// <auto-generated />
using System;
using MasteryBlog.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MasteryBlog.Migrations
{
    [DbContext(typeof(BlogContext))]
    partial class BlogContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.8-servicing-32085")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MasteryBlog.Models.Destination.Destination", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description");

                    b.Property<string>("Image");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Destinations");

                    b.HasData(
                        new { Id = 1, Description = "Great for family fun", Image = "/Images/FamilyVacation.jpg", Name = "Family Getaway" },
                        new { Id = 2, Description = "Work hard, play hard", Image = "/Images/BusinessTrip.jpg", Name = "Business Trip" },
                        new { Id = 3, Description = "Top of the buckeklist", Image = "Images/Retirement.jpg", Name = "Retirement" },
                        new { Id = 4, Description = "Paradise", Image = "Images/Honeymoon.jpg", Name = "Honeymoon" }
                    );
                });

            modelBuilder.Entity("MasteryBlog.Models.Post.Post", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Author");

                    b.Property<string>("Body");

                    b.Property<string>("Category");

                    b.Property<DateTime>("PublishDate");

                    b.Property<string>("Tags");

                    b.Property<string>("Title");

                    b.HasKey("ID");

                    b.ToTable("Posts");
                });
#pragma warning restore 612, 618
        }
    }
}
